language: ruby
rvm: system

matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      osx_image: xcode9

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)";
      LINUXBREW="/home/linuxbrew/.linuxbrew";
      FORMULA="libbi-linux";
      export PATH="$LINUXBREW/bin:$LINUXBREW/sbin:$PATH";
      brew tap sbfnk/libbi;
      chmod 644 $LINUXBREW/Homebrew/Library/Taps/sbfnk/homebrew-libbi/"$FORMULA".rb;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      export FORMULA="libbi";
      brew cask uninstall --force oclint;
      brew tap sbfnk/libbi;
    fi

script:
  - brew update
  - brew --env
  - brew config
  - brew readall --aliases sbfnk/libbi
  - brew uses --recursive --HEAD "sbfnk/libbi/$FORMULA"
  - brew fetch --retry --HEAD "sbfnk/libbi/$FORMULA"
  - brew install --only-dependencies --verbose "sbfnk/libbi/$FORMULA"; true
  - brew install --verbose --HEAD "sbfnk/libbi/$FORMULA"
  - brew audit "sbfnk/libbi/$FORMULA" --online
  - brew linkage "sbfnk/libbi/$FORMULA"
  - brew linkage --test "sbfnk/libbi/$FORMULA"
  - brew test --verbose --HEAD "sbfnk/libbi/$FORMULA"
  - brew uninstall --force "sbfnk/libbi/$FORMULA"
  - brew install "sbfnk/libbi/$FORMULA" --HEAD
  - brew test --HEAD "sbfnk/libbi/$FORMULA"
