language: ruby
rvm: 2.3.0

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
  allow_failures:
    - os: linux

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo mkdir -p /home/linuxbrew;
      sudo chown "$USER" /home/linuxbrew;
      LINUXBREW=/home/linuxbrew/.linuxbrew;
      git clone https://github.com/Linuxbrew/brew.git "$LINUXBREW";
      export PATH="$LINUXBREW/bin:$PATH";
      brew install --build-from-source perl;
    fi

script:
  - brew tap sbfnk/libbi;
  - brew install libbi-sbfnk --HEAD;

# notifications:
#   email:
#     on_success: never
#     on_failure: always
