language: ruby
rvm: system

matrix:
  include:
    - os: linux
      sudo: false
    - os: osx
      osx_image: xcode9

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo mkdir -p /home/linuxbrew;
      sudo chown "$USER" /home/linuxbrew;
      LINUXBREW=/home/linuxbrew/.linuxbrew;
      git clone https://github.com/Linuxbrew/brew.git "$LINUXBREW";
      export PATH="$LINUXBREW/bin:$PATH";
      brew tap sbfnk/libbi;
      chmod 644 /home/linuxbrew/.linuxbrew/Library/Taps/sbfnk/homebrew-libbi/libbi.rb;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew cask uninstall --force oclint;
      brew tap sbfnk/libbi;
    fi

script:
  - brew --env
  - brew config
  - brew readall --aliases sbfnk/libbi
  - brew uses --recursive --HEAD sbfnk/libbi/libbi
  - brew fetch --retry --HEAD sbfnk/libbi/libbi
  - brew install --only-dependencies --verbose sbfnk/libbi/libbi
  - brew install --verbose --HEAD sbfnk/libbi/libbi
  - brew audit sbfnk/libbi/libbi --online
  - brew linkage sbfnk/libbi/libbi
  - brew linkage --test sbfnk/libbi/libbi
  - brew test --verbose --HEAD sbfnk/libbi/libbi
  - brew uninstall --force sbfnk/libbi/libbi
  - brew install libbi --HEAD
  - brew test --HEAD libbi
