language: ruby
os: linux
rvm: 2.0.0

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
  allow_failures:
    - os: linux

script: ./travis/script.sh

# notifications:
#   email:
#     on_success: never
#     on_failure: always
