language: ruby
rvm: 2.3.0

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo mkdir -p /home/linuxbrew;
      sudo chown "$USER" /home/linuxbrew;
      LINUXBREW=/home/linuxbrew/.linuxbrew;
      git clone https://github.com/Linuxbrew/brew.git "$LINUXBREW";
      export PATH="$LINUXBREW/bin:$PATH";
      brew update;
      brew install --build-from-source perl;
      brew tap sbfnk/libbi;
      chmod 644 /home/linuxbrew/.linuxbrew/Library/Taps/sbfnk/homebrew-libbi/libbi-sbfnk.rb;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
      brew tap sbfnk/libbi;
    fi

script:
  - brew --env
  - brew config
  - brew readall --aliases sbfnk/libbi
  - brew uses --recursive --HEAD sbfnk/libbi/libbi-sbfnk
  - brew cask uninstall --force oclint
  - brew fetch --retry --HEAD sbfnk/libbi/libbi-sbfnk
  - brew install --only-dependencies --verbose sbfnk/libbi/libbi-sbfnk
  - brew install --verbose --HEAD sbfnk/libbi/libbi-sbfnk
  - brew audit sbfnk/libbi/libbi-sbfnk --online
  - brew linkage sbfnk/libbi/libbi-sbfnk
  - brew linkage --test sbfnk/libbi/libbi-sbfnk
  - brew test --verbose --HEAD sbfnk/libbi/libbi-sbfnk
  - brew uninstall --force sbfnk/libbi/libbi-sbfnk
  - brew install libbi-sbfnk --HEAD
  - brew test --HEAD libbi-sbfnk
